# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 18:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0010_auto_20161113_1926'),
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=10000)),
                ('creation_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('general_post', models.BooleanField(default=False)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Course')),
                ('tutor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tutor.TutorUser')),
            ],
        ),
    ]
