# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='course',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tutor',
        ),
    ]
