# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_course_post'),
        ('tutor', '0003_remove_tutoruser_post'),
        ('main_posts', '0002_auto_20161113_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='tutor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tutor.TutorUser'),
            preserve_default=False,
        ),
    ]
