# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0003_auto_20161106_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UserProfile')),
            ],
            options={
                'db_table': 'tutor_user',
            },
        ),
    ]
