# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_tutoruser_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutoruser',
            name='post',
        ),
    ]
