# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_remove_tutoruser_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoruser',
            name='allowed_teams_number',
            field=models.IntegerField(default=10),
        ),
    ]
