# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('tutor', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='signed_students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentUser'),
        ),
        migrations.AddField(
            model_name='project',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.TutorUser'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(to='student.StudentUser'),
        ),
        migrations.AddField(
            model_name='course',
            name='tutors',
            field=models.ManyToManyField(to='tutor.TutorUser'),
        ),
    ]
