# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20161106_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentuser',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='tutoruser',
            name='profile',
        ),
        migrations.DeleteModel(
            name='StudentUser',
        ),
        migrations.DeleteModel(
            name='TutorUser',
        ),
    ]
