# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
        ('main', '0002_auto_20161106_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=10000)),
                ('general_post', models.BooleanField(default=False)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Course')),
                ('tutor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tutor.TutorUser')),
            ],
        ),
    ]
