# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 20:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20161107_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creation_date',
            field=models.TimeField(verbose_name=datetime.datetime.now),
        ),
    ]
