# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20161107_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='course',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tutor',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
