# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_posts', '0002_auto_20161113_1935'),
        ('main', '0010_auto_20161113_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_posts.Post'),
            preserve_default=False,
        ),
    ]
