# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-14 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_course_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='signed_students',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.StudentUser'),
        ),
    ]
