# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-14 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20161214_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='allowed_students_number',
            field=models.IntegerField(default=3),
        ),
    ]
