# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-26 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20161214_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='signed_students',
        ),
    ]
