# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-26 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_project_signed_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='minimum_students_number',
            field=models.IntegerField(default=2),
        ),
    ]
