# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_projectteam_accepted'),
        ('main', '0016_project_minimum_students_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=510)),
            ],
        ),
        migrations.CreateModel(
            name='NewProjectTeamMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Message')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewProjectTeamRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('project_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.ProjectTeam')),
            ],
        ),
        migrations.CreateModel(
            name='UserInbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='newprojectteammessage',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.NewProjectTeamRequest'),
        ),
        migrations.AddField(
            model_name='newprojectteammessage',
            name='user_inbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UserInbox'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='inbox',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.UserInbox'),
        ),
    ]
