# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-26 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20161226_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectteam',
            name='students',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.StudentUser'),
        ),
    ]
