# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_remove_projectteam_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectteam',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
