# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-28 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20161228_1300'),
        ('student', '0008_auto_20161228_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentuser',
            name='project_team',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='signed_project',
        ),
        migrations.AddField(
            model_name='projectteam',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Course'),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='project_teams',
            field=models.ManyToManyField(null=True, to='student.ProjectTeam'),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='signed_projects',
            field=models.ManyToManyField(null=True, to='main.Project'),
        ),
    ]
