# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20161228_2121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentuser',
            old_name='project_teams',
            new_name='projectTeams',
        ),
        migrations.RenameField(
            model_name='studentuser',
            old_name='signed_projects',
            new_name='signedProjects',
        ),
    ]
